[package]
name = "wasm"
version = "0.2.0"
authors = ["y21"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
wasm-bindgen = "0.2.63"
dash-core = { path = "../dash-core", features = ["decompile"] }
js-sys = "0.3.57"
