[package]
name = "dash-core"
version = "0.1.2"
authors = ["y21"]
edition = "2018"
license = "MIT"

[features]
decompile = []
s1-type-annotations = []

[dependencies]
dash-proc-macro = { path = "../dash-proc-macro" }
derive_more = "0.99.17"
bitflags = "1.3.2"
