[workspace]
members = [
    "crates/dash-core",
    "crates/dash-cli",
    "crates/testrunner",
    "crates/dash-wasm",
    "crates/dash-proc-macro",
    "crates/dash-rt",
]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.dev]
debug = true
