[workspace]
members = [
    "crates/dash_middle",
    "crates/dash_lexer",
    "crates/dash_parser",
    "crates/dash_compiler",
    "crates/dash_optimizer",
    "crates/dash_vm",
    "crates/dash_core",
    "cli",
    "testrunner",
    "crates/dash_wasm",
    "crates/dash_proc_macro",
    "crates/dash_rt",
    "crates/dash_dlloader",
    "crates/dash_jit",
]

[profile.release]
lto = "fat"
codegen-units = 1

[profile.dev]
debug = true
