[package]
name = "runtime"
version = "0.1.0"
edition = "2018"
license = "MIT"

[features]
# Implements `Math.random()` using the rand crate
random = ["rand"]

[dependencies]
dash = { path = "../dash-core/" }
rand = { version = "0.8.4", optional = true }
