[package]
name = "dash-cli"
version = "0.1.0"
edition = "2018"


[dependencies]
dash = { path = "../dash-core" }
runtime = { path = "../dash-rt", features = ["random"] }
structopt = "0.3"
console = "0.14.1"
backtrace = "0.3.61"
