[package]
name = "dash_vm"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
jit = ["dash_llvm_jit_backend"]
eval = ["dash_compiler", "dash_parser", "dash_lexer", "dash_optimizer"]

[dependencies]
dash_middle = { path = "../dash_middle" }
dash_proc_macro = { path = "../dash_proc_macro" }
dash_lexer = { path = "../dash_lexer", optional = true }
dash_parser = { path = "../dash_parser", optional = true }
dash_compiler = { path = "../dash_compiler", features = [
    "from_string",
], optional = true }
dash_optimizer = { path = "../dash_optimizer", optional = true }
dash_regex = { path = "../dash_regex" }
dash_llvm_jit_backend = { path = "../dash_llvm_jit_backend", optional = true }
bitflags = "1.3.2"
smallvec = { version = "1.9.0", features = ["const_generics"] }

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false }

[[bench]]
name = "full"
harness = false
